name: Trigger Main Repo Update

on:
  push:
    branches:
      - master   # 当 master 分支有推送时触发

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch to main repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PAT }}" \
            https://api.github.com/repos/gotoded/sunnypilot/dispatches \
            -d '{"event_type":"update-opendbc"}'
